---
- name: Add golang PPA
  apt_repository:
    repo: ppa:gophers/archive

- name: Install Golang 1.11
  apt:
    name: golang-1.11-go
    update_cache: yes
    state: latest

- name: Add some stuff to .bashrc to get $PATH and GO111MODULE=on
  blockinfile:
    path: "/home/{{ username }}/.bashrc"
    marker: "# {mark} ANSIBLE-MANAGED GOLANG-STUFF"
    block: |
      export GO111MODULE=on
      export GOROOT=/usr/lib/go-1.11
      export PATH=$PATH:/usr/lib/go-1.11/bin:/home/{{ username }}/go/bin

- name: Update alternatives to get link in /usr/bin
  alternatives:
    name: go
    path: /usr/lib/go-1.11/bin/go
