---

- name: Install all the nice stuff
  ansible.builtin.apt:
    name:
      - bind9utils
      - cloudsql-proxy
      - curl
      - direnv
      - git
      - ipcalc
      - jq
      - keepassxc
      - pwgen
      - python3-dev
      - python3-venv
      - python3-virtualenv
      - shellcheck
      - sway
      - vim
      - whois
      - yq
    state: present

- name: Install aws-google-auth
  ansible.builtin.pip:
    name: aws-google-auth
    virtualenv: /opt/aws-google-auth
