---
- name: Copy git-prompt.sh
  ansible.builtin.copy:
    src: git-prompt.sh
    dest: "/usr/local/bin/git-prompt.sh"
    mode: 0755
    owner: root
    group: root

- name: Copy git-promt bashrc.d-file
  ansible.builtin.copy:
    src: git-prompt.bashrc
    dest: "/home/{{ common_useruser }}/.bashrc.d/git-prompt.bashrc"
    owner: "{{ common_useruser }}"
    group: "{{ common_useruser }}"
    mode: 0444
