---

- name: Copy keymaps
  ansible.builtin.copy:
    src: "keymaps/{{ item }}"
    dest: "/usr/share/X11/xkb/symbols/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - se
    - gb
