---

- name: Copy keymaps
  ansible.builtin.copy:
    src: "keymaps/{{ item }}"
    dest: "/usr/share/X11/xkb/symbols/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - se
    - gb

- name: Copy bashrc-additions
  ansible.builtin.copy:
    src: "bashrc.d/{{ item }}"
    dest: "/home/{{ common_useruser }}/.bashrc.d/{{ item }}"
    owner: "{{ common_useruser }}"
    group: "{{ common_useruser }}"
    mode: 0444
  loop:
    - vi-mode.bashrc
    - direnv.bashrc

- name: Source .bashrc.d content
  ansible.builtin.blockinfile:
    path: "/home/{{ common_useruser }}/.bashrc"
    block: |
      for file in ~/.bashrc.d/*.bashrc
      do
        source "$file"
      done
