---

- name: Copy keymaps
  ansible.builtin.copy:
    src: "keymaps/{{ item }}"
    dest: "/usr/share/X11/xkb/symbols/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - se
    - gb

- name: Add sourcing of .bashrc.d content
  ansible.builtin.blockinfile:
    path: "/home/{{ common_useruser }}/.bashrc"
    block: |
      for file in ~/.bashrc.d/*.bashrc
      do
        source "$file"
      done

- name: Make sure we have the needed folders
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0700
  loop:
    - "/home/{{ common_useruser }}/.gnupg"
    - "/home/{{ common_useruser }}/.ssh"

- name: Copy a bunch of dotfiles
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '{{ item.mode | default("0444") }}'
    owner: "{{ common_useruser }}"
    group: "{{ common_useruser }}"
  loop:
    - { src: "bashrc.d/direnv.bashrc", dest: "/home/{{ common_useruser }}/.bashrc.d/direnv.bashrc" }
    - { src: "bashrc.d/kubectl.bashrc", dest: "/home/{{ common_useruser }}/.bashrc.d/kubectl.bashrc" }
    - { src: "bashrc.d/vi-mode.bashrc", dest: "/home/{{ common_useruser }}/.bashrc.d/vi-mode.bashrc" }
    - { src: "bashrc.d/gnupg.bashrc", dest: "/home/{{ common_useruser }}/.bashrc.d/gnupg.bashrc" }
    - { src: "gnupg/gpg-agent.conf", dest: "/home/{{ common_useruser }}/.gnupg/gpg-agent.conf" }
