---
- name: Add Microsoft's signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

- name: Install VS Code
  apt:
    name: code
    update_cache: yes
    state: latest
