---
- name: Append extra bashrc-stuff
  blockinfile:
    path: "/home/{{ username }}/.bashrc"
    block: "{{ lookup('file', '../files/bashrc') }}"
    marker: "# {mark} GENERAL BASHRC-STUFF FROM ANSIBLE"
