---
- name: Install packages
  apt:
    name:
      - pcscd
      - scdaemon
    update_cache: yes

- name: Add configuration
  copy:
    src: "files/{{ item }}"
    dest: "/home/{{ username }}/.gnupg/{{ item }}"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Restart gpg-agent
  become: "{{ username }}"
  become_method: sudo
  command: "gpg-connect-agent killagent /bye && gpg-connect-agent /bye"

- name: GPG-stuff needed in environment
  blockinfile:
    path: "/home/{{ username }}/.bashrc"
    marker: "# {mark} GPG-AGENT STUFF FROM ANSIBLE"
    block: |
      export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh
      export GPG_TTY=$(tty)
