---
- name: Install packages
  apt:
    name:
      - pcscd
      - scdaemon
    update_cache: yes

- name: Add configuration
  copy:
    src: "files/{{ item }}"
    dest: "/home/{{ username }}/.gnupg/{{ item }}"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Restart gpg-agent
  command: "sudo -u {{ username }} gpg-connect-agent killagent /bye && sudo -u {{ username }} gpg-connect-agent /bye"
