---
- name: Add key for VirtualBox-repo
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Add VirtualBox-repo
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian bionic contrib
    state: present

- name: Install VirtualBox
  apt:
    name: virtualbox
    state: latest
    update_cache: yes
