---
- name: Add apt-key for Docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt-repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: Install docker-ce
  apt:
    name: docker-ce
    update_cache: yes
    state: latest
