---
- name: Install vim
  apt:
    name:
      - vim
      - cmake
      - python-dev
      - python3-dev

    state: latest
    update_cache: yes

- name: Get vundle
  become: false
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/home/{{ username }}/.vim/bundle/Vundle.vim"

- name: Copy .vimrc
  copy:
    src: files/vimrc
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
