---

- name: Download terraform-docs {{ tdocs_version.number }}
  ansible.builtin.get_url:
    url: '{{ tdocs_remoteurl }}'
    dest: '{{ tdocs_localtargz }}'
    checksum: sha256:{{ tdocs_version.sha256 }}
    owner: root
    group: root
    mode: 0444

- name: Create terraform-docs {{ tdocs_version.number }} install dir
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - '{{ tdocs_basedir }}'
    - '{{ tdocs_installdir }}'

- name: Install terraform-docs {{ tdocs_version.number }}
  ansible.builtin.unarchive:
    remote_src: True
    src: '{{ tdocs_localtargz }}'
    dest: '{{ tdocs_installdir }}'
    owner: root
    group: root
    creates: '{{ tdocs_installdir }}/terraform-docs'

- name: Setup terraform-docs {{ tdocs_version.number }} symlinks
  ansible.builtin.file:
    src: '{{ tdocs_installdir }}/terraform-docs'
    dest: /usr/local/bin/terraform-docs
    state: link
  register: reg_tdocs_current

- name: Generate terraform-docs bash completion
  ansible.builtin.shell:
    cmd: '{{ tdocs_installdir }}/terraform-docs completion bash > /etc/bash_completion.d/terraform-docs'
  when: reg_tdocs_current is changed
